Сделал задание 2.1
javacore2017/lw2-1-ilyarom pull request #1
Opened 2017-11-07 08:11 UTC by ilyarom

Здравствуйте! Сделал задание 2.1 (Супермаркет)

2017-11-13 20:45 UTC, mrkurbatov requested changes
Требуются доработки. Так же не нашел батника для компиляции и запуска.

2017-11-13 20:45 UTC, mrkurbatov commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Не должно быть папки .idea

2017-11-13 20:45 UTC, mrkurbatov commented on src/net/volgatech/CashDesk.java
> +                switch (element.getDiscountType()) {
Не используйте свичи. Используйте полиморфизм. https://refactoring.guru/replace-conditional-with-polymorphism

2017-11-13 20:45 UTC, mrkurbatov commented on src/net/volgatech/Customer/Basket.java
> +        return _products;
Зачем нижнее подчеркивание?

2017-11-13 20:45 UTC, mrkurbatov commented on src/net/volgatech/Customer/Customer.java
> +    }
Все сущности должны быть в отдельных файлах: enums, classes, interfaces

2017-11-13 20:45 UTC, mrkurbatov commented on src/net/volgatech/Handler/Main.java
> +            }, random.nextInt(8) * 1000);
В мастере не должно быть закоментированного кода

2017-11-13 21:04 UTC, ilyarom commented on src/net/volgatech/Customer/Basket.java
> +        return _products;
Исправил

2017-11-13 21:04 UTC, ilyarom commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Исправил

2017-11-13 21:06 UTC, ilyarom commented on src/net/volgatech/Handler/Main.java
> +            }, random.nextInt(8) * 1000);
Исправил

2017-11-13 21:37 UTC, ilyarom commented on src/net/volgatech/Customer/Customer.java
> +    }
Исправил

2017-11-18 15:21 UTC, ilyarom commented on src/net/volgatech/CashDesk.java
> +                switch (element.getDiscountType()) {
Исправил

2017-11-18 15:21 UTC, ilyarom commented
Исправил указанные ошибки

2017-11-20 16:04 UTC, ilyarom commented
Исправил

2017-11-13 23:45 GMT+03:00 mrkurbatov <notifications@github.com>:

> *@mrkurbatov* requested changes on this pull request.
>
> Требуются доработки. Так же не нашел батника для компиляции и запуска.
> ------------------------------
>
> In .idea/misc.xml
> <https://github.com/javacore2017/lw2-1-ilyarom/pull/1#discussion_r150656653>
> :
>
> > @@ -0,0 +1,12 @@
> +<?xml version="1.0" encoding="UTF-8"?>
>
> Не должно быть папки .idea
> ------------------------------
>
> In src/net/volgatech/CashDesk.java
> <https://github.com/javacore2017/lw2-1-ilyarom/pull/1#discussion_r150657219>
> :
>
> > +import net.volgatech.Report.Bill;
> +
> +import java.math.BigDecimal;
> +import java.time.LocalDateTime;
> +import java.util.ArrayList;
> +import java.util.List;
> +
> +public class CashDesk {
> +    BigDecimal _cashMachineAmount = new BigDecimal(0);
> +    private List<Discount> _discounts = new ArrayList<Discount>();
> +    private List<Product> _products = new ArrayList<Product>();
> +    private Double getDiscountCoefficient(Customer customer, Product product) {
> +        double coefficient = 1;
> +        for (Discount element : _discounts) {
> +            if (element.getProductType().equals(product.getType())) {
> +                switch (element.getDiscountType()) {
>
> Не используйте свичи. Используйте полиморфизм. https://refactoring.guru/
> replace-conditional-with-polymorphism
> ------------------------------
>
> In src/net/volgatech/Customer/Basket.java
> <https://github.com/javacore2017/lw2-1-ilyarom/pull/1#discussion_r150657559>
> :
>
> > @@ -0,0 +1,16 @@
> +package net.volgatech.Customer;
> +
> +import net.volgatech.Product;
> +
> +import java.util.ArrayList;
> +import java.util.List;
> +
> +public class Basket {
> +    private List<Product> _products = new ArrayList<Product>();
> +    public List<Product> getProducts() {
> +        return _products;
>
> Зачем нижнее подчеркивание?
> ------------------------------
>
> In src/net/volgatech/Customer/Customer.java
> <https://github.com/javacore2017/lw2-1-ilyarom/pull/1#discussion_r150658216>
> :
>
> > +package net.volgatech.Customer;
> +
> +import net.volgatech.Product;
> +
> +public class Customer {
> +    private Basket basket = new Basket();
> +    private PaymentMethod paymentMethod;
> +    public enum Type {
> +        CHILD,
> +        ADULT,
> +        RETIRED;
> +        @Override
> +        public String toString() {
> +            return super.toString().toLowerCase();
> +        }
> +    }
>
> Все сущности должны быть в отдельных файлах: enums, classes, interfaces
> ------------------------------
>
> In src/net/volgatech/Handler/Main.java
> <https://github.com/javacore2017/lw2-1-ilyarom/pull/1#discussion_r150658453>
> :
>
> > +            timer.schedule(new TimerTask() {
> +                public void run() {
> +                    supermarket.AddCustomer(values.customerTypes.get(random.nextInt(2)), values.paymentMethods.get(random.nextInt(1)));
> +                    Timer timer2 = new Timer();
> +                    for (Integer j = 0; j < random.nextInt(5); ++j) {
> +                        timer2.schedule(new TimerTask() {
> +                            @Override
> +                            public void run() {
> +                                Customer customer = supermarket.getCustomer(i);
> +                                List<Product> products = Supermarket.getProductList();
> +                                customer.PushToBasket(products.get(random.nextInt(products.size() - 1)));
> +                            }
> +                        }, random.nextInt(4) * 1000);
> +                    }
> +                }
> +            }, random.nextInt(8) * 1000);
>
> В мастере не должно быть закоментированного кода
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/javacore2017/lw2-1-ilyarom/pull/1#pullrequestreview-76239472>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ASoXnP-DFh88Ak4vFfkgN5XM1HJb4Aakks5s2KpmgaJpZM4QUZvg>
> .
>

2017-11-21 06:40 UTC, mrkurbatov requested changes
Коэффициент 0.6
Сделайте Inspect code в IDE, пофиксите основные баги

2017-11-21 06:40 UTC, mrkurbatov commented on src/net/volgatech/Discount/CashPaymentDiscount.java
> +            return (1 - value);
Некорректное сравнение ссылочных типов

2017-11-22 18:21 UTC, ilyarom commented on src/net/volgatech/Discount/CashPaymentDiscount.java
> +            return (1 - value);
Поправил

2017-11-22 18:21 UTC, ilyarom commented
Сделал, поправил

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-21 9:40 GMT+03:00 mrkurbatov <notifications@github.com>:

> *@mrkurbatov* requested changes on this pull request.
>
> Коэффициент 0.6
> Сделайте Inspect code в IDE, пофиксите основные баги
> ------------------------------
>
> In src/net/volgatech/Discount/CashPaymentDiscount.java
> <https://github.com/javacore2017/lw2-1-ilyarom/pull/1#discussion_r152189097>
> :
>
> > @@ -0,0 +1,17 @@
> +package net.volgatech.Discount;
> +
> +import net.volgatech.Customer.Customer;
> +import net.volgatech.Customer.PaymentMethod.MethodType;
> +import net.volgatech.Customer.PaymentMethod.PaymentMethod;
> +
> +public class CashPaymentDiscount extends DiscountType {
> +    public double getDiscountCoefficient(Customer customer, double value) {
> +        if (customer.getPaymentMethod() == MethodType.CASH)
> +            return (1 - value);
>
> Некорректное сравнение ссылочных типов
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/javacore2017/lw2-1-ilyarom/pull/1#pullrequestreview-78011278>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ASoXnBoGXWoyDJbwqqtUFp-Y-vB6n0GPks5s4nBwgaJpZM4QUZvg>
> .
>

2017-11-27 19:22 UTC, merged